export const SQLITE_ENTITY_ID = {
	AccountBudgetLink: 1,
	CategoryAssigment: 2,
	CommonSettings: 3,
	Image: 4,
	InvestmentAccountTotalValue: 5,
	StringHistoryItem: 6,
	SyncCommand: 7,
	SyncObject: 8,
	Account: 9,
	BankChequeAccount: 10,
	BankSavingAccount: 11,
	CashAccount: 12,
	CreditCardAccount: 13,
	LoanAccount: 14,
	InvestmentAccount: 15,
	ForexAccount: 16,
	AppSettings: 17,
	Budget: 18,
	Category: 19,
	CustomFormsOption: 20,
	CustomReport: 21,
	Group: 22,
	InfoCard: 23,
	InvestmentHolding: 24,
	OnlineBank: 25,
	OnlineBankAccount: 26,
	OnlineBankUser: 27,
	Payee: 28,
	PaymentPlan: 29,
	PaymentPlanItem: 30,
	ScheduledTransactionHandler: 31,
	ScheduledDepositTransactionHandler: 32,
	ScheduledTransferTransactionHandler: 33,
	ScheduledWithdrawTransactionHandler: 34,
	Tag: 35,
	Transaction: 36,
	DepositTransaction: 37,
	InvestmentExchangeTransaction: 38,
	InvestmentTransaction: 39,
	InvestmentBuyTransaction: 40,
	InvestmentSellTransaction: 41,
	ReconcileTransaction: 42,
	RefundTransaction: 43,
	TransferBudgetTransaction: 44,
	TransferDepositTransaction: 45,
	TransferWithdrawTransaction: 46,
	WithdrawTransaction: 47,
	TransactionBudgetLink: 48,
	User: 49,
	WithdrawRefundTransactionLink: 50,
} as const

export type SQLiteEntityName = keyof typeof SQLITE_ENTITY_ID
export type SQLiteEntityId = (typeof SQLITE_ENTITY_ID)[SQLiteEntityName]

export const SQLITE_ACCOUNT_ENTITY_RANGE = {
	min: SQLITE_ENTITY_ID.BankChequeAccount,
	max: SQLITE_ENTITY_ID.ForexAccount,
} as const

export const SQLITE_ACCOUNT_ENTITY_IDS = [
	SQLITE_ENTITY_ID.BankChequeAccount,
	SQLITE_ENTITY_ID.BankSavingAccount,
	SQLITE_ENTITY_ID.CashAccount,
	SQLITE_ENTITY_ID.CreditCardAccount,
	SQLITE_ENTITY_ID.LoanAccount,
	SQLITE_ENTITY_ID.InvestmentAccount,
	SQLITE_ENTITY_ID.ForexAccount,
] as const

export const SQLITE_CORE_ENTITY_IDS = {
	category: SQLITE_ENTITY_ID.Category,
	payee: SQLITE_ENTITY_ID.Payee,
	tag: SQLITE_ENTITY_ID.Tag,
	transaction: SQLITE_ENTITY_ID.Transaction,
	user: SQLITE_ENTITY_ID.User,
	commonSettings: SQLITE_ENTITY_ID.CommonSettings,
} as const
